name: Java CI/CD Flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Set permissions for mvnw
      run: chmod +x mvnw
      
    - name: Build Docker Image
      run: docker build -t tranducvu/gk-springboot-new:latest .

    - name: Push Docker Image
      run: |
        docker tag tranducvu/gk-springboot-new:latest tranducvu/gk-springboot-new:latest
        docker push tranducvu/gk-springboot-new:latest
